- name: Copying files from source to destination
  hosts: webservers
  gather_facts: true
  tasks:
    - name: including role
      include_role: copy

    - name: Including editing file
      include_role: Editingfile
      
